export const categories = [
  {viewValue: 'Animali', value: 'animals'},
  {viewValue: 'Architettura', value: 'architecture'},
  {viewValue: 'Autobiografia', value: 'autobiographies'},
  {viewValue: 'Biologia', value: 'biology'},
  {viewValue: 'Chimica', value: 'chemistry'},
  {viewValue: 'Cucina', value: 'cooking'},
  {viewValue: 'Fantasy', value: 'fantasy'},
  {viewValue: 'Film', value: 'film'},
  {viewValue: 'Finanza', value: 'finance'},
  {viewValue: 'Fotografia', value: 'photography'},
  {viewValue: 'Horror', value: 'horror'},
  {viewValue: 'Letteratura', value: 'literature'},
  {viewValue: 'Magia', value: 'magic'},
  {viewValue: 'Management', value: 'management'},
  {viewValue: 'Matematica', value: 'mathematics'},
  {viewValue: 'Musica', value: 'music'},
  {viewValue: 'Pittura', value: 'painting'},
  {viewValue: 'Programmazione', value: 'programming'},
  {viewValue: 'Religione', value: 'religion'},
  {viewValue: 'Storia', value: 'history'},
  {viewValue: 'Thriller', value: 'thriller'},
]
